import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit';
import { RootState, Land } from './types';
import { fetchUserData } from '@/api/fetchUserData';
import axios from "axios";

// Define the initial state for the land slice
const initialState: { lands: Land[] | null } = {
  lands: null,
};

// Create an asynchronous thunk to fetch and register land details
export const fetchAndRegisterLands = createAsyncThunk(
  'land/fetchAndRegisterLands',
  async (userId: string) => {
    const userData = await fetchUserData(userId);
    return userData.land;
  }
);

// Create an asynchronous thunk to Delete land details
export const deleteLandAsync = createAsyncThunk(
    'land/deleteLandAsync',
    async (landId: string) => {
      const url = `http://localhost:5000/api/land/deleteLand/${landId}`;
      try {
        const response = await axios.delete(url);
        // Handle the response
        return landId; // Assuming successful deletion, return the deleted land ID
      } catch (error) {
        console.error('Error deleting land:', error);
        throw error; // Re-throw the error for handling in the reducer
      }
    }
);

// Create the land slice using createSlice function
const landSlice = createSlice({
  name: 'land',
  initialState,
  reducers: {
    // Reducer function to register land details
    registerLands: (state, action: PayloadAction<Land[] | null>) => {
      state.lands = action.payload;
    },
    // Add a new land
    addNewLand: (state, action: PayloadAction<Land>) => {
      if (state.lands) {
        state.lands.push(action.payload);
      }
    },
    // Delete a land
    deleteLand: (state, action: PayloadAction<string>) => {
      if (state.lands) {
        state.lands = state.lands.filter((land) => land._id !== action.payload);
      }
    },
    // Edit a land
    editLand: (state, action: PayloadAction<Land>) => {
      if (state.lands) {
        const updatedLand = action.payload;
        state.lands = state.lands.map((land) => (land._id === updatedLand._id ? updatedLand : land));
      }
    },
  },
  // Define extra reducers for handling asynchronous actions
  extraReducers: (builder) => {
    builder
      // Handle successful fulfillment of fetchAndRegisterLands
      .addCase(fetchAndRegisterLands.fulfilled, (state, action: PayloadAction<Land[]>) => {
        state.lands = action.payload;
      })
      // Handle rejection of fetchAndRegisterLands
      .addCase(fetchAndRegisterLands.rejected, (state, action) => {
        console.error('Error fetching land details:', action.error);
      })
        // Handle successful fulfillment of deleteLandAsync
      .addCase(deleteLandAsync.fulfilled, (state, action: PayloadAction<string>) => {
        const deletedLandId = action.payload;
        if (state.lands) {
          state.lands = state.lands.filter((land) => land._id !== deletedLandId);
        }
      })
        // Handle rejection of deleteLandAsync
        .addCase(deleteLandAsync.rejected, (state, action) => {
          console.error('Error deleting land:', action.error);
        })

  },
});

// Export the reducer and actions from the land slice
export const { registerLands, addNewLand, deleteLand, editLand } = landSlice.actions;

// Selector to retrieve land details from the state
// Refactored the selectLand to accept a more generic state object any), instead of expecting the RootState type
export const selectLands = (state: any) => state.land.lands;

// Export the reducer function generated by createSlice
export default landSlice.reducer;
