import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit';
import { RootState, User } from './types';
import { fetchUserData } from '@/api/fetchUserData';
import { updateUserData } from '@/api/updateUserData';

// Define the initial state for the user slice
const initialState: { user: User | null } = {
  user: null,
};

// Define an async thunk action creator to fetch and register user details
export const fetchAndRegisterUser = createAsyncThunk(
  'user/fetchAndRegisterUser',
  async (userId: string) => {
    // Fetch user data using the provided userId
    const userData = await fetchUserData(userId);
    // Return the user data fetched from the API
    return userData.user;
  }
);

// Create an asynchronous thunk to update user details
export const updateUserAsync = createAsyncThunk(
  "user/updateUserAsync",
  async (userData: User) => {
    // Call the updateUserData function with the provided user data
    const user = await updateUserData(userData);
    // Return the updated user data
    return user;
  }
);

// Create a slice for managing user state
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    // Define a reducer function to register user details
    register: (state, action) => {
      // Update the user details in the state based on the action payload
      state.user = action.payload;
    },
    // Edit user details
    editUser: (state, action: PayloadAction<User>) => {
      if (state.user) {
      const updatedUser = action.payload;
      state.user = { ...state.user, ...updatedUser };
      }
    },
  },
  // Handle extra reducers for async actions
  extraReducers: (builder) => {
    // Handle the fulfilled action of fetchAndRegisterUser
    builder.addCase(fetchAndRegisterUser.fulfilled, (state, action: PayloadAction<User>) => {
      // Update the user details in the state based on the action payload
      state.user = action.payload;
    });

    // Handle successful fulfillment of updateUserAsync (assuming optional return)
    builder.addCase(updateUserAsync.fulfilled, (state, action) => {
  const updatedUserData = action.payload.user;
  if (state.user) {
    state.user = { ...state.user, ...updatedUserData };
  }
})
    .addCase(updateUserAsync.rejected, (state, action) => {
      console.error("Error updating user:", action.error);
      // Handle errors (e.g., revert UI update, display error message)
    });

  },
});

// Export the reducer and actions generated by the user slice
export const { register } = userSlice.actions;

// Define a selector function to select user details from the state
export const selectUser = (state: RootState) => state.user.user;

// Export the user reducer
export default userSlice.reducer;
