import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import CssBaseline from '@mui/material/CssBaseline'; // Import the CssBaseline component
import Navbar from "../components/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DOA Cost of Cultivation Reporting System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* Add the CssBaseline component to override the 8px margin */}
      <CssBaseline />
      {/* Add navigation bar */}
      <Navbar /> 
      <div className="container">{children}</div>
      </body>
    </html>
  )
}
